// Generated by cpp11: do not edit by hand
// clang-format off


#include "cpp11/declarations.hpp"

// code.cpp
void fun2(const std::string& name);
extern "C" SEXP _xla_fun2(SEXP name) {
  BEGIN_CPP11
    fun2(cpp11::as_cpp<cpp11::decay_t<const std::string&>>(name));
    return R_NilValue;
  END_CPP11
}

extern "C" {
/* .Call calls */
extern SEXP _xla_fun2(SEXP);

static const R_CallMethodDef CallEntries[] = {
    {"_xla_fun2", (DL_FUNC) &_xla_fun2, 1},
    {NULL, NULL, 0}
};
}

extern "C" void R_init_xla(DllInfo* dll){
  R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
  R_useDynamicSymbols(dll, FALSE);
  R_forceSymbols(dll, TRUE);
}
